

spring:

  profiles:
    #    active: tmp
    include:
      - tmp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



# 브랜치 테스트를 위한 수정사항입니다.


#  security:
#    user:
#      name: admin
#      password: admin

jwt:
  secret: YourJWTSecretKey
  expiration: 604800 # 7 days in seconds
  token-prefix: "Bearer "
  header-string: "Authorization"
