spring:

#  profiles:
    #    active: tmp
#    include:
#      - tmp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tranvel?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ssafy0000

#  security:
#    user:
#      name: admin
#      password: admin

jwt:
  header: Authorization
  # must use over 512bit secret key, cause of HS512 algorithm
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 86400 # ttl (초)
