spring:
  profiles:
    active: local
    include:
      - secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  data:
    redis:
      host: localhost
      port: 6379
# change for commit

#  security:
#    user:
#      name: admin
#      password: admin

jwt:
  secret: YourJWTSecretKey
  expiration: 604800 # 7 days in seconds
  token-prefix: "Bearer "
  header-string: "Authorization"

