spring:
  profiles:
    active: local
    group:
      local: secret
      set1: blue, secret
      set2: green, secret


---
spring:
  config:
    activate:
      on-profile: blue


server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081

